version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: fastpassword
      POSTGRES_DB: abuelitosBack
    ports:
      - 5433:5432